"""
Phase 0 — run all feasibility checks and produce the Definition-of-Done report:
a short markdown report (numbers) + one plot, quotable in a pitch.
"""
from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from feasibility.coverage_estimate import run_coverage_estimate  # noqa: E402
from feasibility.gpu_check import run_gpu_check  # noqa: E402
from feasibility.scale_recovery import run_full_sweep  # noqa: E402

REPORTS_DIR = REPO_ROOT / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


def make_scale_error_plot(scale_results, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 5))
    noise_levels = sorted(set(r.gps_noise_std_m for r in scale_results))
    frame_counts = sorted(set(r.n_camera_positions for r in scale_results))

    for noise in noise_levels:
        ys = [
            next(r.mean_abs_scale_error_pct for r in scale_results
                 if r.gps_noise_std_m == noise and r.n_camera_positions == fc)
            for fc in frame_counts
        ]
        ax.plot(frame_counts, ys, marker="o", label=f"GPS noise σ={noise}m")

    ax.axhline(5.0, color="red", linestyle="--", linewidth=1, label="5% target (PRD.md)")
    ax.set_xlabel("Number of camera positions (post Phase-1 keyframes)")
    ax.set_ylabel("Mean absolute scale error (%)")
    ax.set_title("Phase 0: Synthetic GPS-noise scale-recovery error")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main() -> None:
    print("Running GPU capability check...")
    gpu_report = run_gpu_check()

    print("Running synthetic GPS-noise scale-recovery sweep...")
    scale_results = run_full_sweep()

    print("Running single-pass coverage estimate...")
    coverage_result = run_coverage_estimate()

    plot_path = REPORTS_DIR / "phase0_scale_error.png"
    make_scale_error_plot(scale_results, plot_path)

    raw = {
        "gpu": asdict(gpu_report),
        "scale_recovery_sweep": [asdict(r) for r in scale_results],
        "coverage": asdict(coverage_result),
    }
    (REPORTS_DIR / "phase0_raw_results.json").write_text(json.dumps(raw, indent=2))

    # Pull out the "primary" numbers for the headline quote (2.5m GPS noise = typical
    # consumer drone GPS without RTK, 150 keyframes = a realistic post-filter count).
    primary = next(
        r for r in scale_results
        if r.gps_noise_std_m == 2.5 and r.n_camera_positions == 150
    )
    worst_case = next(
        r for r in scale_results
        if r.gps_noise_std_m == 5.0 and r.n_camera_positions == 50
    )

    report_md = f"""# Phase 0 — Feasibility Harness Report

**Generated by:** `src/feasibility/run_phase0.py`
**Hardware:** {gpu_report.device_name or "N/A"}, \
{f"{gpu_report.total_vram_mb:.0f}MiB VRAM" if gpu_report.total_vram_mb else "no CUDA device"}, \
driver {gpu_report.driver_version}, CUDA runtime {gpu_report.cuda_runtime_version}

## 1. GPU Capability

- CUDA available to PyTorch: **{gpu_report.cuda_available}**
- Device: **{gpu_report.device_name}**
- VRAM: **{f"{gpu_report.total_vram_mb:.0f} MiB" if gpu_report.total_vram_mb else "N/A"}**
- Recommendation: {gpu_report.recommendation}

## 2. Synthetic GPS-Noise Scale-Recovery Error

Method: Umeyama similarity alignment between a simulated SfM camera trajectory (correct
shape, unknown scale) and a GPS-measured trajectory (real-world meters + Gaussian noise),
Monte-Carlo over 200 trials per configuration. See `src/feasibility/scale_recovery.py`.

**Headline number (typical case — consumer GPS, σ=2.5m, 150 keyframes):**
mean scale error **{primary.mean_abs_scale_error_pct:.2f}%** (p90: {primary.p90_scale_error_pct:.2f}%)
— well within the **5%** target from PRD.md Section 5.

**Worst realistic case (degraded GPS σ=5.0m, only 50 keyframes):**
mean scale error **{worst_case.mean_abs_scale_error_pct:.2f}%** (p90: {worst_case.p90_scale_error_pct:.2f}%)
— still within target.

Full sweep (GPS noise × keyframe count) plotted in `reports/phase0_scale_error.png`.

**Caveat (log this honestly, don't oversell):** this model captures *random* per-frame GPS
noise, which the similarity alignment averages out across many camera positions (error
shrinks roughly as 1/sqrt(N)). It does **not** model *systematic* GPS bias (e.g. constant
antenna lever-arm offset, correlated multipath in a single flight) which averaging cannot
remove. Real-world scale error will likely be higher than this simulation suggests. Treat
these numbers as a best-case lower bound, not a guarantee — revisit once real flight GPS
logs are available.

## 3. Single-Pass Coverage Estimate

Method: synthetic city (18 axis-aligned buildings + ground), single straight-line flight
pass at 80m altitude with a 25° forward-tilted gimbal (not pure nadir — chosen to balance
rooftop and facade capture), 70°-FOV camera, frustum + backface + AABB-occlusion
visibility test per surface sample point. See `src/feasibility/coverage_estimate.py`.

- **Overall surface coverage: {coverage_result.coverage_pct_overall:.1f}%**
- Ground: {coverage_result.coverage_pct_by_class.get('ground', 0):.1f}%
- Roofs: {coverage_result.coverage_pct_by_class.get('roof', 0):.1f}%
- Facades: {coverage_result.coverage_pct_by_class.get('facade', 0):.1f}%

**Interpretation:** a single straight-line pass leaves roughly \
{100 - coverage_result.coverage_pct_overall:.0f}% of scene surface area unobserved —
facades are the weakest category (only one side of most buildings is ever in view from a
single heading), which is expected and exactly why PRD.md Section 5 requires *honest*
coverage reporting (Phase 6) rather than presenting a complete-looking mesh. A real
flight with a lawnmower/grid pattern or multiple headings would substantially improve
facade coverage, but that changes the "single pass" premise — this number is the
realistic honest baseline for the literal single-line case.

## Quotable summary for a pitch

> "Synthetic testing shows our GPS-based scale recovery achieves {primary.mean_abs_scale_error_pct:.1f}% \
mean error under realistic consumer-GPS noise — well inside our 5% target — while a single \
flight pass leaves an estimated {100 - coverage_result.coverage_pct_overall:.0f}% of scene \
surface area unobserved, which is why we report per-region confidence rather than presenting \
the model as complete."
"""
    (REPORTS_DIR / "phase0_report.md").write_text(report_md, encoding="utf-8")
    print(f"\nReport written to {REPORTS_DIR / 'phase0_report.md'}")
    print(f"Plot written to {plot_path}")


if __name__ == "__main__":
    main()
